### ISSUE TITLE
IPA input?

### ISSUE THREAD

**Issue by t3db0t** [kdelwat/Onset#14]
Hi there—obviously this is 4 years old but it could be exactly what I'm looking for to experiment with what english would sound like in a far-future setting.

However, the IPA input doesn't seem to be working. When I input `ˈdʒʌŋɡəl`, it gives me `unknown character`. I looked through the YAML but it seems like there are only certain unicode characters allowed? Is this expecting some specific form of IPA that I'm not familiar with?

Thanks :)

**Comment by kdelwat** [comment]
Hi, thanks for filing an issue - apologies I didn't get to this sooner.

Are you running Onset locally, or using the hosted version at onset.cadel.me? I'm not able to reproduce your issue - your input is working for me:

![image](https://user-images.githubusercontent.com/1031518/125729328-d1cee30e-31f3-4918-a90c-41a6641b3e6b.png)

**Comment by t3db0t** [comment]
Hm, it works for me now, not sure what happened. Thanks for checking! :D
