### ISSUE TITLE
Potential bug with 'Vowel Nasalization' rule application

### ISSUE THREAD

**Issue by CNakai** [kdelwat/Onset#7]
I'm not sure if this is intended behavior or not, but I noticed that when the rule, "Vowels become nasalized after nasal consonants," the rule did not apply to **long** vowels after nasal consonants. I recognize that this may be intended behavior but I thought I'd bring it to your attention anyway.

**Comment by kdelwat** [comment]
This probably shouldn't be happening, I'll check it out. Thanks!

**Comment by kdelwat** [comment]
Fixed in version 2.0.1. Thanks!

**Comment by CNakai** [comment]
Hey, no worries. Glad to be of help!
