### ISSUE TITLE
Application is not reachable. 

### ISSUE THREAD

**Issue by alexeykosh** [kdelwat/Onset#9]
It seems that the online version of the application is not working. 
![Screen Shot 2019-11-21 at 15 31 46](https://user-images.githubusercontent.com/19796224/69346997-0c47e780-0c74-11ea-94d8-003d3ea62bb4.png)

**Comment by judah-caruso** [comment]
I found it! It's here now: https://onset.cadel.me/

**Comment by alexeykosh** [comment]
Thanks a lot!
